In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle
import requests
import json
from sklearn.preprocessing import StandardScaler
from datetime import date, datetime
from path import Path
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.preprocessing import OneHotEncoder
import tensorflow as tf

In [57]:
# Importing the dataset
df = pd.read_csv('./data/encoded_Bird.csv')
y = df.species_num
X = df.drop(["species_num", "Unnamed: 0"], axis=1)

df

,Unnamed: 0,AQI,heavy_rain,high_wind,Year,Population,species_num,counties_num,parameter_num,season_num
0,0,46,0,1,2018,905801.0,1,1,1,1
1,1,77,0,0,2018,905801.0,1,1,1,2
2,2,90,0,1,2018,905801.0,1,1,1,1
3,3,46,0,1,2018,905801.0,5,1,1,1
4,4,46,0,1,2018,905801.0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...
1371287,1371287,23,0,0,2016,1160.0,4,54,2,4
1371288,1371288,65,0,0,2016,1160.0,4,54,2,4
1371289,1371289,65,0,0,2016,1160.0,1,54,2,4
1371290,1371290,58,0,0,2012,1166.0,1,54,2,4
1371291,1371291,58,0,0,2012,1166.0,6,54,2,4

In [58]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [59]:
# Scale 
from sklearn.preprocessing import StandardScaler

# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [60]:
# Decision Tree
# Setting max decision tree depth to help avoid overfitting
dt2 = DecisionTreeClassifier(max_depth=3)
dt2.fit(X_train_scaled, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=3, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [61]:
# Predicting the Test set results
y_pred = dt2.predict(X_test)

In [62]:
# Saving model to disk
pickle.dump(dt2, open('model.pkl','wb'))

In [56]:

# Loading model to compare the results
model = pickle.load( open('model.pkl','rb'))
print(model.predict([[1,1,1,1,1,1,1,1]]))

[1]